// src/constants.tsx
import type { Program } from './types';

export const programs: Program[] = [
  // SEGUNDA A SÁBADO
  {
    id: 'mon1',
    title: 'MADRUGADA COM CRISTO',
    host: 'Samuel Andrade',
    startTime: '00:00',
    endTime: '06:00',
    description: 'Início da madrugada com música e mensagens de fé.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Samuel_Andrade_vbvhtd.webp',
  },
  {
    id: 'mon2',
    title: 'PRAISE FM WORSHIP BRASIL',
    host: '',
    startTime: '06:00',
    endTime: '07:00',
    description: 'Louvor e adoração ao vivo.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Praise_FM_Worship_jv3c0c.webp',
  },
  {
    id: 'mon3',
    title: 'MANHÃ COM CRISTO',
    host: 'Lucas Martins',
    startTime: '07:00',
    endTime: '12:00',
    description: 'Comece seu dia com mensagens de fé e músicas gospel.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205840/Lucas_Martins_weoryq.webp',
  },
  {
    id: 'mon4',
    title: 'PRAISE FM WORSHIP BRASIL',
    host: '',
    startTime: '12:00',
    endTime: '13:00',
    description: 'Louvor e adoração ao vivo.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Praise_FM_Worship_jv3c0c.webp',
  },
  {
    id: 'mon5',
    title: 'TARDE GOSPEL',
    host: 'Rafael Costa',
    startTime: '13:00',
    endTime: '16:00',
    description: 'Músicas gospel para sua tarde.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Rafael_Costa_a7mlpu.webp',
  },
  {
    id: 'mon6',
    title: 'PRAISE FM NON STOP',
    host: '',
    startTime: '16:00',
    endTime: '17:00',
    description: 'Hits nonstop para alegrar seu dia.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205840/Praise_FM_Non_Stop_jzk8wz.webp',
  },
  {
    id: 'mon7',
    title: 'PRAISE FM NOVA GERAÇÃO',
    host: 'Ana Paula',
    startTime: '17:00',
    endTime: '18:00',
    description: 'Programa jovem com músicas e mensagens inspiradoras.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205840/Ana_Paula_nqsvtl.webp',
  },
  {
    id: 'mon8',
    title: 'DE CARONA COM A PRAISE FM',
    host: 'Bruno Almeida',
    startTime: '18:00',
    endTime: '20:00',
    description: 'Boa música para acompanhar seu trajeto.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205840/Bruno_Almeida_xsixw6.webp',
  },
  {
    id: 'mon9',
    title: 'PRAISE FM LIVE SHOW',
    host: '',
    startTime: '20:00',
    endTime: '21:00',
    description: 'Transmissão ao vivo, somente quarta-feira.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205840/Praise_Fm_Live_Show_blfy7o.webp',
  },
  {
    id: 'mon10',
    title: 'PRAISE FM BRASIL CLÁSSICOS',
    host: 'Rodrigo Veras',
    startTime: '21:00',
    endTime: '22:00',
    description: 'Os grandes clássicos do gospel brasileiro.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Rodrigo_Veras_vpjwxi.webp',
  },
  {
    id: 'mon11',
    title: 'PRAISE FM WORSHIP BRASIL',
    host: '',
    startTime: '22:00',
    endTime: '00:00',
    description: 'Louvor e adoração ao vivo.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Praise_FM_Worship_jv3c0c.webp',
  },

  // DOMINGO
  {
    id: 'sun1',
    title: 'MADRUGADA COM CRISTO',
    host: 'Samuel Andrade',
    startTime: '00:00',
    endTime: '06:00',
    description: 'Início da madrugada com música e mensagens de fé.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Samuel_Andrade_vbvhtd.webp',
  },
  {
    id: 'sun2',
    title: 'PRAISE FM WORSHIP BRASIL',
    host: '',
    startTime: '06:00',
    endTime: '07:00',
    description: 'Louvor e adoração ao vivo.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Praise_FM_Worship_jv3c0c.webp',
  },
  {
    id: 'sun3',
    title: 'DOMINGO COM CRISTO',
    host: 'Felipe Santos',
    startTime: '07:00',
    endTime: '12:00',
    description: 'Mensagens e músicas para o seu domingo.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205840/Felipe_Santos_a2bdvs.webp',
  },
  {
    id: 'sun4',
    title: 'PRAISE FM WORSHIP BRASIL',
    host: '',
    startTime: '12:00',
    endTime: '13:00',
    description: 'Louvor e adoração ao vivo.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Praise_FM_Worship_jv3c0c.webp',
  },
  {
    id: 'sun5',
    title: 'TARDE GOSPEL',
    host: 'Rafael Costa',
    startTime: '13:00',
    endTime: '16:00',
    description: 'Músicas gospel para sua tarde.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Rafael_Costa_a7mlpu.webp',
  },
  {
    id: 'sun6',
    title: 'PRAISE FM NON STOP',
    host: '',
    startTime: '16:00',
    endTime: '17:00',
    description: 'Hits nonstop para alegrar seu dia.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205840/Praise_FM_Non_Stop_jzk8wz.webp',
  },
  {
    id: 'sun7',
    title: 'PRAISE FM NOVA GERAÇÃO',
    host: 'Ana Paula',
    startTime: '17:00',
    endTime: '18:00',
    description: 'Programa jovem com músicas e mensagens inspiradoras.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205840/Ana_Paula_nqsvtl.webp',
  },
  {
    id: 'sun8',
    title: 'PRAISE FM WORSHIP BRASIL',
    host: '',
    startTime: '18:00',
    endTime: '20:00',
    description: 'Louvor e adoração ao vivo.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Praise_FM_Worship_jv3c0c.webp',
  },
  {
    id: 'sun9',
    title: 'PRAISE FM POP',
    host: 'Thiago Moreira',
    startTime: '20:00',
    endTime: '21:00',
    description: 'Pop gospel em todos os dias da semana.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Thiago_Moreira_yicuhk.webp',
  },
  {
    id: 'sun10',
    title: 'PRAISE FM BRASIL CLÁSSICOS',
    host: 'Rodrigo Veras',
    startTime: '21:00',
    endTime: '22:00',
    description: 'Os grandes clássicos do gospel brasileiro.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Rodrigo_Veras_vpjwxi.webp',
  },
  {
    id: 'sun11',
    title: 'PREGAÇÃO DA PALAVRA',
    host: '',
    startTime: '22:00',
    endTime: '23:00',
    description: 'Mensagens de fé e reflexão.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Prega%C3%A7%C3%A3o_da_Palavra_zdphb4.webp',
  },
  {
    id: 'sun12',
    title: 'PRAISE FM WORSHIP BRASIL',
    host: '',
    startTime: '23:00',
    endTime: '00:00',
    description: 'Louvor e adoração ao vivo.',
    image: 'https://res.cloudinary.com/dlcliu2cv/image/upload/v1769205841/Praise_FM_Worship_jv3c0c.webp',
  },
];
